"""
Decision Routing Mixin
Created: 2024-12-25 (P7.3)
Modularized: 2026-01-02 (RULE-032)

Handles routing decisions to TypeDB with evidence file generation.
"""
from typing import Dict, Any
from datetime import datetime
from dataclasses import asdict
from pathlib import Path

from governance.router.models import RouteResult

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent.parent
EVIDENCE_DIR = PROJECT_ROOT / "evidence"


class DecisionRoutingMixin:
    """Mixin for decision routing operations."""

    def route_decision(
        self,
        decision_id: str,
        name: str,
        context: str = "",
        rationale: str = "",
        impacts: str = "",
        status: str = "ACTIVE",
        create_evidence: bool = False
    ) -> Dict[str, Any]:
        """
        Route a new decision to TypeDB.

        Args:
            decision_id: Decision ID (e.g., "DECISION-005")
            name: Decision name
            context: Decision context
            rationale: Decision rationale
            impacts: Expected impacts
            status: Decision status
            create_evidence: Create evidence markdown file

        Returns:
            RouteResult as dict
        """
        # Validate
        if not decision_id:
            return asdict(RouteResult(
                success=False,
                destination='none',
                item_type='decision',
                item_id=decision_id,
                error='decision_id is required'
            ))

        # Pre-hook
        data = {
            'decision_id': decision_id,
            'name': name,
            'context': context,
            'rationale': rationale,
            'impacts': impacts,
            'status': status
        }
        if self.pre_route_hook:
            data = self.pre_route_hook('decision', data)

        # Generate TypeQL
        typeql = self._generate_decision_typeql(**data)

        # Execute
        embedded = False
        evidence_file = None

        if not self.dry_run:
            success = self._execute_typeql(typeql)
            if success and self.embed and self.embedding_pipeline:
                self.embedding_pipeline.embed_decision(
                    decision_id,
                    f"{name}: {context}"
                )
                embedded = True

            if success and create_evidence:
                evidence_file = self._create_decision_evidence(data)
        else:
            success = True
            embedded = self.embed
            if create_evidence:
                evidence_file = f"evidence/{decision_id}.md (dry run)"

        result = asdict(RouteResult(
            success=success,
            destination='typedb',
            item_type='decision',
            item_id=decision_id,
            embedded=embedded,
            evidence_file=evidence_file
        ))

        if self.post_route_hook:
            self.post_route_hook('decision', result)

        return result

    def _generate_decision_typeql(
        self,
        decision_id: str,
        name: str,
        context: str = "",
        rationale: str = "",
        impacts: str = "",
        status: str = "ACTIVE"
    ) -> str:
        """Generate TypeQL insert for decision."""
        return f'''
            insert $d isa decision,
                has decision-id "{self._escape(decision_id)}",
                has decision-name "{self._escape(name)}",
                has decision-context "{self._escape(context)}",
                has decision-rationale "{self._escape(rationale)}",
                has decision-impacts "{self._escape(impacts)}",
                has decision-status "{self._escape(status)}",
                has decision-date {datetime.now().isoformat()};
        '''

    def _create_decision_evidence(self, data: Dict) -> str:
        """Create evidence markdown file for decision."""
        filepath = EVIDENCE_DIR / f"{data['decision_id']}.md"
        content = f"""# {data['decision_id']}: {data['name']}

**Date:** {datetime.now().isoformat()}
**Status:** {data.get('status', 'ACTIVE')}

## Context

{data.get('context', 'No context provided.')}

## Rationale

{data.get('rationale', 'No rationale provided.')}

## Expected Impacts

{data.get('impacts', 'No impacts specified.')}

---
*Generated by governance/router (P7.3)*
"""
        filepath.write_text(content)
        return str(filepath)
